/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExampleLoansIndexRouteImport } from './routes/example.loans/index'
import { Route as ExampleLoansLoanIdRouteImport } from './routes/example.loans/$loanId'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExampleLoansIndexRoute = ExampleLoansIndexRouteImport.update({
  id: '/example/loans/',
  path: '/example/loans/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExampleLoansLoanIdRoute = ExampleLoansLoanIdRouteImport.update({
  id: '/example/loans/$loanId',
  path: '/example/loans/$loanId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/example/loans/$loanId': typeof ExampleLoansLoanIdRoute
  '/example/loans': typeof ExampleLoansIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/example/loans/$loanId': typeof ExampleLoansLoanIdRoute
  '/example/loans': typeof ExampleLoansIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/example/loans/$loanId': typeof ExampleLoansLoanIdRoute
  '/example/loans/': typeof ExampleLoansIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/mcp' | '/example/loans/$loanId' | '/example/loans'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/mcp' | '/example/loans/$loanId' | '/example/loans'
  id: '__root__' | '/' | '/mcp' | '/example/loans/$loanId' | '/example/loans/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  McpRoute: typeof McpRoute
  ExampleLoansLoanIdRoute: typeof ExampleLoansLoanIdRoute
  ExampleLoansIndexRoute: typeof ExampleLoansIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/example/loans/': {
      id: '/example/loans/'
      path: '/example/loans'
      fullPath: '/example/loans'
      preLoaderRoute: typeof ExampleLoansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/example/loans/$loanId': {
      id: '/example/loans/$loanId'
      path: '/example/loans/$loanId'
      fullPath: '/example/loans/$loanId'
      preLoaderRoute: typeof ExampleLoansLoanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  McpRoute: McpRoute,
  ExampleLoansLoanIdRoute: ExampleLoansLoanIdRoute,
  ExampleLoansIndexRoute: ExampleLoansIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
